---
- name: Set hostname to inventory_hostname_short
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"
    use: systemd
  notify: Reboot system
  become: true
  become_user: root

- name: Force run the handlers
  ansible.builtin.meta: flush_handlers
