---

- name: set hostname to inventory_hostname_short
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"
    use: systemd
  notify: reboot system

- name: force run the handlers
  meta: flush_handlers
